package serialize

// constants contained in hessian2 protocol
const (
	BC_BINARY                uint8 = 'B'  // final chunk
	BC_BINARY_CHUNK          uint8 = 'A'  // non-final chunk
	BC_BINARY_DIRECT         uint8 = 0x20 // 1-byte length binary
	BINARY_DIRECT_MAX        uint8 = 0x0f
	BC_BINARY_SHORT          uint8 = 0x34  // 2-byte length binary
	BINARY_SHORT_MAX         uint8 = 0x3ff // 0-1023 binary
	BC_CLASS_DEF             uint8 = 'C'   // object/class definition
	BC_DATE                  uint8 = 0x4a  // 64-bit millisecond UTC date
	BC_DATE_MINUTE           uint8 = 0x4b  // 32-bit minute UTC date
	BC_DOUBLE                uint8 = 'D'   // IEEE 64-bit double
	BC_DOUBLE_ZERO           uint8 = 0x5b
	BC_DOUBLE_ONE            uint8 = 0x5c
	BC_DOUBLE_BYTE           uint8 = 0x5d
	BC_DOUBLE_SHORT          uint8 = 0x5e
	BC_DOUBLE_MILL           uint8 = 0x5f
	BC_FALSE                 uint8 = 'F' // boolean false
	BC_INT                   uint8 = 'I' // 32-bit uint8
	INT_DIRECT_MIN           uint8 = -0x10
	INT_DIRECT_MAX           uint8 = 0x2f
	BC_INT_ZERO              uint8 = 0x90
	INT_BYTE_MIN             uint8 = -0x800
	INT_BYTE_MAX             uint8 = 0x7ff
	BC_INT_BYTE_ZERO         uint8 = 0xc8
	BC_END                   uint8 = 'Z'
	INT_SHORT_MIN            uint8 = -0x40000
	INT_SHORT_MAX            uint8 = 0x3ffff
	BC_INT_SHORT_ZERO        uint8 = 0xd4
	BC_LIST_VARIABLE         uint8 = 0x55
	BC_LIST_FIXED            uint8 = 'V'
	BC_LIST_VARIABLE_UNTYPED uint8 = 0x57
	BC_LIST_FIXED_UNTYPED    uint8 = 0x58
	BC_LIST_DIRECT           uint8 = 0x70
	BC_LIST_DIRECT_UNTYPED   uint8 = 0x78
	LIST_DIRECT_MAX          uint8 = 0x7
	BC_LONG                  uint8 = 'L' // 64-bit signed uint8eger
	BC_LONG_ZERO             uint8 = 0xe0
	LONG_DIRECT_MIN          uint8 = -0x08
	LONG_DIRECT_MAX          uint8 = 0x0f
	LONG_BYTE_MIN            uint8 = -0x800
	LONG_BYTE_MAX            uint8 = 0x7ff
	BC_LONG_BYTE_ZERO        uint8 = 0xf8
	LONG_SHORT_MIN           uint8 = -0x40000
	LONG_SHORT_MAX           uint8 = 0x3ffff
	BC_LONG_SHORT_ZERO       uint8 = 0x3c
	BC_LONG_INT              uint8 = 0x59
	BC_MAP                   uint8 = 'M'
	BC_MAP_UNTYPED           uint8 = 'H'
	BC_NULL                  uint8 = 'N'
	BC_OBJECT                uint8 = 'O'
	BC_OBJECT_DEF            uint8 = 'C'
	BC_OBJECT_DIRECT         uint8 = 0x60
	OBJECT_DIRECT_MAX        uint8 = 0x0f
	BC_REF                   uint8 = 0x51
	BC_STRING                uint8 = 'S' // final string
	BC_STRING_CHUNK          uint8 = 'R' // non-final string
	BC_STRING_DIRECT         uint8 = 0x00
	STRING_DIRECT_MAX        uint8 = 0x1f
	BC_STRING_SHORT          uint8 = 0x30
	STRING_SHORT_MAX         uint8 = 0x3ff
	BC_TRUE                  uint8 = 'T'
	P_PACKET_CHUNK           uint8 = 0x4f
	P_PACKET                 uint8 = 'P'
	P_PACKET_DIRECT          uint8 = 0x80
	PACKET_DIRECT_MAX        uint8 = 0x7f
	P_PACKET_SHORT           uint8 = 0x70
	PACKET_SHORT_MAX         uint8 = 0xfff
)
