package serialize

// constants contained in hessian2 protocol
const (
	BC_BINARY                int   = 'B'  // final chunk
	BC_BINARY_CHUNK          int   = 'A'  // non-final chunk
	BC_BINARY_DIRECT         int   = 0x20 // 1-byte length binary
	BINARY_DIRECT_MAX        int   = 0x0f
	BC_BINARY_SHORT          int   = 0x34  // 2-byte length binary
	BINARY_SHORT_MAX         int   = 0x3ff // 0-1023 binary
	BC_CLASS_DEF             int   = 'C'   // object/class definition
	BC_DATE                  int   = 0x4a  // 64-bit millisecond UTC date
	BC_DATE_MINUTE           int   = 0x4b  // 32-bit minute UTC date
	BC_DOUBLE                int   = 'D'   // IEEE 64-bit double
	BC_DOUBLE_ZERO           int   = 0x5b
	BC_DOUBLE_ONE            int   = 0x5c
	BC_DOUBLE_BYTE           int   = 0x5d
	BC_DOUBLE_SHORT          int   = 0x5e
	BC_DOUBLE_MILL           int   = 0x5f
	BC_FALSE                 int   = 'F' // boolean false
	BC_INT                   int   = 'I' // 32-bit int
	INT_DIRECT_MIN           int   = -0x10
	INT_DIRECT_MAX           int   = 0x2f
	BC_INT_ZERO              uint8   = 0x90
	INT_BYTE_MIN             int   = -0x800
	INT_BYTE_MAX             int   = 0x7ff
	BC_INT_BYTE_ZERO         uint8   = 0xc8
	BC_END                   int   = 'Z'
	INT_SHORT_MIN            int   = -0x40000
	INT_SHORT_MAX            int   = 0x3ffff
	BC_INT_SHORT_ZERO        uint8   = 0xd4
	BC_LIST_VARIABLE         int   = 0x55
	BC_LIST_FIXED            int   = 'V'
	BC_LIST_VARIABLE_UNTYPED int   = 0x57
	BC_LIST_FIXED_UNTYPED    int   = 0x58
	BC_LIST_DIRECT           int   = 0x70
	BC_LIST_DIRECT_UNTYPED   int   = 0x78
	LIST_DIRECT_MAX          int   = 0x7
	BC_LONG                  int   = 'L' // 64-bit signed integer
	BC_LONG_ZERO             uint8   = 0xe0
	LONG_DIRECT_MIN          int64 = -0x08
	LONG_DIRECT_MAX          int64 = 0x0f
	LONG_BYTE_MIN            int64 = -0x800
	LONG_BYTE_MAX            int64 = 0x7ff
	BC_LONG_BYTE_ZERO        uint8   = 0xf8
	LONG_SHORT_MIN           int   = -0x40000
	LONG_SHORT_MAX           int   = 0x3ffff
	BC_LONG_SHORT_ZERO       uint8   = 0x3c
	BC_LONG_INT              uint8   = 0x59
	BC_MAP                   int   = 'M'
	BC_MAP_UNTYPED           int   = 'H'
	BC_NULL                  int   = 'N'
	BC_OBJECT                int   = 'O'
	BC_OBJECT_DEF            int   = 'C'
	BC_OBJECT_DIRECT         int   = 0x60
	OBJECT_DIRECT_MAX        int   = 0x0f
	BC_REF                   int   = 0x51
	BC_STRING                int   = 'S' // final string
	BC_STRING_CHUNK          int   = 'R' // non-final string
	BC_STRING_DIRECT         int   = 0x00
	STRING_DIRECT_MAX        int   = 0x1f
	BC_STRING_SHORT          int   = 0x30
	STRING_SHORT_MAX         int   = 0x3ff
	BC_TRUE                  int   = 'T'
	P_PACKET_CHUNK           int   = 0x4f
	P_PACKET                 int   = 'P'
	P_PACKET_DIRECT          int   = 0x80
	PACKET_DIRECT_MAX        int   = 0x7f
	P_PACKET_SHORT           int   = 0x70
	PACKET_SHORT_MAX         int   = 0xfff
)
